# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      name: Flake8
      description: "Flake8: Your Tool For Style Guide Enforcement"
      entry: flake8 .
      additional_dependencies:
        - flake8-bandit==2.1.2
        - flake8-bugbear==19.8.0
        - flake8-comprehensions==3.0.1
        - flake8-debugger==3.2.1
        - flake8-deprecated==1.3
        - flake8-pep3101==1.2.1
        - flake8-polyfill==1.0.2
        - bandit==1.7.2 # flake8-bandit dependency breaks without this version

- repo: https://github.com/psf/black
  rev: '21.12b0'
  hooks:
    - id: black
      name: Black
      description: "Black: The uncompromising Python code formatter"
      entry: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      language_version: python3.9
